@FieldsManagement.WebApi_HostAddress = http://localhost:7138

POST {{FieldsManagement.WebApi_HostAddress}}/Fields/
Content-Type: application/json

{
  "Id": "123",
  "VillageName": "ExampleVillage",
  "Area": 123.45,
  "additionalData": "Some additional data"
}

###
